name: Setup Docker Image
description: Build or restore cached Docker image for talawanda-enews
outputs:
  cache-hit:
    description: Whether the Docker image was restored from cache
    value: ${{ steps.cache-image.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Generate Docker image cache key
      id: docker-cache-key
      shell: bash
      run: |
        # Create hash of Dockerfile and requirements.txt only
        # Code is mounted at runtime, not baked into image
        if [ ! -f Dockerfile ] || [ ! -f requirements.txt ]; then
          echo "ERROR: Required files (Dockerfile and/or requirements.txt) not found"
          exit 1
        fi
        HASH=$(cat Dockerfile requirements.txt | sha256sum | cut -d' ' -f1)
        echo "hash=$HASH" >> $GITHUB_OUTPUT
        echo "Docker image hash: $HASH"

    - name: Check for cached Docker image
      id: cache-image
      uses: actions/cache@v4
      with:
        path: /tmp/talawanda-enews.tar
        key: docker-image-${{ steps.docker-cache-key.outputs.hash }}

    - name: Set up Docker Buildx
      if: steps.cache-image.outputs.cache-hit != 'true'
      uses: docker/setup-buildx-action@v3

    - name: Build and export Docker image
      if: steps.cache-image.outputs.cache-hit != 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: talawanda-enews:latest
        outputs: type=docker,dest=/tmp/talawanda-enews.tar
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Load Docker image
      shell: bash
      run: |
        if [ ! -f /tmp/talawanda-enews.tar ]; then
          echo "ERROR: Docker image tar file not found at /tmp/talawanda-enews.tar"
          exit 1
        fi
        docker load --input /tmp/talawanda-enews.tar
        docker image ls -a

    - name: Save Docker image to cache
      if: steps.cache-image.outputs.cache-hit != 'true' && success()
      uses: actions/cache/save@v4
      with:
        path: /tmp/talawanda-enews.tar
        key: docker-image-${{ steps.docker-cache-key.outputs.hash }}
